version: '3.8'

services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-net

  kafka:
    container_name: kafka
    hostname: kafka
    image: bitnami/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=0
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka-rest:
    container_name: kafka-rest
    image: confluentinc/cp-kafka-rest
    depends_on:
      - kafka
    ports:
      - "8082:8082"
    environment:
      - KAFKA_REST_HOST_NAME=kafka-rest
      - KAFKA_REST_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - kafka-net

  jupyter:
    image: jupyter:latest
    depends_on:
      - kafka
    volumes:
      - ./myjupyter:/notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - kafka-net

  backend:
    build: ./kafka_react_app/backend
    container_name: backend
    ports:
      - "5000:3000"
    environment:
      - PORT=3000
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-net

  frontend:
    build: ./kafka_react_app/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - WDS_SOCKET_PORT=0
    volumes:
      - ./kafka_react_app/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
